# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'websocket-servers'
    static_configs:
      - targets: ['websocket-server-1:3000', 'websocket-server-2:3000', 'websocket-server-3:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-node-1:6379', 'redis-node-2:6379', 'redis-node-3:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']